apiVersion: v2
name: testkube
description: Testkube is an open-source platform that simplifies the deployment and management of automated testing infrastructure.
type: application
<<<<<<< HEAD
version: 1.13.24
dependencies:
  - name: testkube-operator
    version: 1.13.4
=======
version: 1.13.33
dependencies:
  - name: testkube-operator
    version: 1.13.5
>>>>>>> 49babd84375de7d18bf5ff9e568ad956ebbfb5ae
    #repository: https://kubeshop.github.io/helm-charts
    repository: "file://../testkube-operator"
    condition: testkube-operator.enabled
  - name: mongodb
    condition: mongodb.enabled
    version: 12.1.31
    repository: https://charts.bitnami.com/bitnami
  - name: nats
    condition: testkube-api.nats.enabled
    version: 0.19.1
    repository: https://nats-io.github.io/k8s/helm/charts/
  - name: testkube-api
<<<<<<< HEAD
    version: 1.13.7
    #repository: https://kubeshop.github.io/helm-charts
    repository: "file://../testkube-api"
  - name: testkube-dashboard
    version: 1.13.7
=======
    version: 1.13.12
    #repository: https://kubeshop.github.io/helm-charts
    repository: "file://../testkube-api"
  - name: testkube-dashboard
    version: 1.13.5
>>>>>>> 49babd84375de7d18bf5ff9e568ad956ebbfb5ae
    #repository: https://kubeshop.github.io/helm-charts
    repository: "file://../testkube-dashboard"
    condition: testkube-dashboard.enabled
  - name: global
    version: 0.1.1
    #repository: https://kubeshop.github.io/helm-charts
    repository: "file://../global"
